Update static_cli.yml

diff --git a/.github/workflows/static_cli.yml b/.github/workflows/static_cli.yml
--- a/.github/workflows/static_cli.yml
+++ b/.github/workflows/static_cli.yml
@@ -19,6 +19,19 @@ jobs:
       - run: |
           brew install automake gzip
 
+      - name: Install Composer
+        run: |
+          EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
+          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+          ACTUAL_CHECKSUM="$(php -r 'echo hash_file("sha384", "composer-setup.php");')"
+          if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then
+              >&2 echo 'ERROR: Invalid installer checksum'
+              rm composer-setup.php
+              exit 1
+          fi
+          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
+          rm composer-setup.php
+
       - name: Paths
         run: |
           echo "ARTIFACT_NAME=php-${{ matrix.php-versions }}-glfw-cli-macos-x86_64" >> $GITHUB_ENV
